version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
      time: '10:00'
      timezone: 'Europe/London'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'deps'
    groups:
      dev-security-updates:
        dependency-type: 'development'
        update-types:
          - 'patch'
          - 'minor'
